linters:
  enable-all: true
  disable:
    - maligned
    - interfacer
issues:
  exclude-use-default: false
  exclude:
    # should have a package comment, unless it's in another file for this package (golint)
    - 'in another file for this package'
    # exported type `Hoge` should have comment or be unexported (golint)
    - 'should have comment or be unexported'
linters-settings:
  # minimal code complexity to report, 30 by default (but we recommend 10-20)
  gocyclo:
    min-complexity: 10
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  govet:
    # report about shadowed variables
    check-shadowing: true
output:
  format: colored-line-number
  print-issued-lines: false
  print-linter-name: true
